# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iot.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='iot.proto',
  package='grpc_test',
  syntax='proto3',
  serialized_options=b'\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tiot.proto\x12\tgrpc_test\"\x1f\n\x07Request\x12\x14\n\x0crequest_data\x18\x02 \x01(\t\" \n\x0cResponseData\x12\x10\n\x08moisture\x18\x01 \x01(\x03\"9\n\x08Response\x12-\n\x0cResponseData\x18\x02 \x01(\x0b\x32\x17.grpc_test.ResponseData2I\n\x03IoT\x12\x42\n\x15ServerStreamingMethod\x12\x12.grpc_test.Request\x1a\x13.grpc_test.Response0\x01\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3'
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='grpc_test.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_data', full_name='grpc_test.Request.request_data', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=55,
)


_RESPONSEDATA = _descriptor.Descriptor(
  name='ResponseData',
  full_name='grpc_test.ResponseData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='moisture', full_name='grpc_test.ResponseData.moisture', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=89,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='grpc_test.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ResponseData', full_name='grpc_test.Response.ResponseData', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=148,
)

_RESPONSE.fields_by_name['ResponseData'].message_type = _RESPONSEDATA
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['ResponseData'] = _RESPONSEDATA
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'iot_pb2'
  # @@protoc_insertion_point(class_scope:grpc_test.Request)
  })
_sym_db.RegisterMessage(Request)

ResponseData = _reflection.GeneratedProtocolMessageType('ResponseData', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEDATA,
  '__module__' : 'iot_pb2'
  # @@protoc_insertion_point(class_scope:grpc_test.ResponseData)
  })
_sym_db.RegisterMessage(ResponseData)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'iot_pb2'
  # @@protoc_insertion_point(class_scope:grpc_test.Response)
  })
_sym_db.RegisterMessage(Response)


DESCRIPTOR._options = None

_IOT = _descriptor.ServiceDescriptor(
  name='IoT',
  full_name='grpc_test.IoT',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=150,
  serialized_end=223,
  methods=[
  _descriptor.MethodDescriptor(
    name='ServerStreamingMethod',
    full_name='grpc_test.IoT.ServerStreamingMethod',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_IOT)

DESCRIPTOR.services_by_name['IoT'] = _IOT

# @@protoc_insertion_point(module_scope)
