# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import iot_pb2 as iot__pb2


class IoTStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ServerStreamingMethod = channel.unary_stream(
                '/grpc_test.IoT/ServerStreamingMethod',
                request_serializer=iot__pb2.Request.SerializeToString,
                response_deserializer=iot__pb2.Response.FromString,
                )


class IoTServicer(object):
    """The greeting service definition.
    """

    def ServerStreamingMethod(self, request, context):
        """server streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IoTServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ServerStreamingMethod': grpc.unary_stream_rpc_method_handler(
                    servicer.ServerStreamingMethod,
                    request_deserializer=iot__pb2.Request.FromString,
                    response_serializer=iot__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc_test.IoT', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IoT(object):
    """The greeting service definition.
    """

    @staticmethod
    def ServerStreamingMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpc_test.IoT/ServerStreamingMethod',
            iot__pb2.Request.SerializeToString,
            iot__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
